name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run check:types

      - name: Lint
        run: npm run lint || echo "Lint step failed; continuing"

      - name: Unit tests (vitest)
        run: npm run test:unit -- --run

      - name: Coverage (vitest)
        run: npm run test:coverage -- --run

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
          if-no-files-found: warn

      - name: Security audit (non-blocking)
        run: npm audit --audit-level=high || echo "Audit found issues"

      - name: API test script
        run: npm test || echo "API test script non-blocking"
